// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3QLQj-ujm49BwR9YmntDw1bmrgFG6eqE',
    appId: '1:455105179926:web:f3f96d0a8c56525a252037',
    messagingSenderId: '455105179926',
    projectId: 'voice-cv-generator',
    authDomain: 'voice-cv-generator.firebaseapp.com',
    storageBucket: 'voice-cv-generator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1nyA35cqrQJueX2lfmHaYqLUpiApbN8',
    appId: '1:455105179926:android:10171e545d17801e252037',
    messagingSenderId: '455105179926',
    projectId: 'voice-cv-generator',
    storageBucket: 'voice-cv-generator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmfwm_AsQPROLIiQWaI39Esj9xyE_VhHc',
    appId: '1:455105179926:ios:8bf88b2f3887e623252037',
    messagingSenderId: '455105179926',
    projectId: 'voice-cv-generator',
    storageBucket: 'voice-cv-generator.firebasestorage.app',
    androidClientId: '455105179926-il3fns53cbik5tf8mvrcp8hd7rn1fb9g.apps.googleusercontent.com',
    iosClientId: '455105179926-vao63a43e72ga0fh7789csjt0m1oceag.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvapp',
  );

}